services:
  - type: web
    name: sarva-flask
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    disk:
      name: whisper-cache
      mountPath: /whisper-cache
      sizeGB: 2
